# Generated by Django 4.1.7 on 2023-04-16 02:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20230415_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(limit_choices_to='CREATOR', to=settings.AUTH_USER_MODEL, verbose_name='Follow'),
        ),
    ]
